"""Markdown rendering for evaluation output and, from Step 7, for cited answers.

Every number written here comes from an object produced by a real run. Nothing in
this module invents, rounds up, or fills in a plausible-looking value.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from .config import Config
from .evaluate import ConfigResult, ThresholdEvidence
from .labels import LabelSet
from .rerank import histogram

CONFIG_LABELS = {
    "dense": "Dense only (bge-m3)",
    "sparse": "Sparse only (FTS5 BM25)",
    "hybrid": "Hybrid, RRF k=60",
    "hybrid_rerank": "Hybrid + cross-encoder rerank",
}


def write_eval_report(
    cfg: Config,
    results: Sequence[ConfigResult],
    labels: LabelSet,
    evidence: ThresholdEvidence | None,
) -> Path:
    n_items = len(results[0].items) if results else 0
    lines: list[str] = []
    add = lines.append

    add("# Evaluation report")
    add("")
    add("Generated by `research-agent eval-retrieval`. Every figure below traces to "
        "this run; nothing is carried over from another project or estimated.")
    add("")
    add(f"- Corpus fingerprint: `{labels.fingerprint_at_labelling}`")
    add(f"- Questions: {len(labels.items)} total, **{n_items} answerable** "
        f"(scored here), {len(labels.controls)} controls")
    add(f"- Embedding model: `{cfg.embed_model}` · Reranker: `{cfg.rerank_model}`")
    add("")

    add("## 1 · Retrieval ablation")
    add("")
    add("**Every column in this table is LLM-free.** Retrieval is measured without "
        "generating a token, which is what makes it reproducible on demand, "
        "comparable across providers, and immune to the synthesis-model variance "
        "that makes generation metrics noisy. Generation-dependent columns "
        "(citation precision, abstention accuracy, fact coverage) arrive at Step 12 "
        "and are labelled as such.")
    add("")
    add("| Config | Recall@5 | 95% CI | MRR | nDCG@10 | p50 ms | p95 ms | LLM calls |")
    add("|---|---:|---:|---:|---:|---:|---:|---:|")
    for res in results:
        lo, hi = res.ci95(lambda i: i.recall_at(5))
        add(f"| {CONFIG_LABELS.get(res.config, res.config)} "
            f"| {res.mean(lambda i: i.recall_at(5)):.3f} "
            f"| [{lo:.2f}, {hi:.2f}] "
            f"| {res.mean(lambda i: i.mrr()):.3f} "
            f"| {res.mean(lambda i: i.ndcg_at(10)):.3f} "
            f"| {res.p50_latency():.0f} | {res.p95_latency():.0f} | 0 |")
    add("")
    add(f"> **On the confidence intervals.** The answerable set is {n_items} questions, "
        f"so these means are genuinely uncertain and the intervals are wide. They are "
        f"bootstrap intervals over the per-question scores, printed rather than "
        f"omitted: a bare mean over {n_items} items would imply a precision the sample "
        f"cannot support. Differences smaller than the interval width are not "
        f"differences.")
    add("")

    add("### Per-question Recall@5")
    add("")
    add("Reported per item as well as in aggregate, because with a set this small the "
        "mean can hide a single catastrophic question.")
    add("")
    header = "| Question | " + " | ".join(
        CONFIG_LABELS.get(r.config, r.config) for r in results) + " |"
    add(header)
    add("|---" * (len(results) + 1) + "|")
    ids = [i.item_id for i in results[0].items] if results else []
    for qid in ids:
        row = [qid]
        for res in results:
            item = next((i for i in res.items if i.item_id == qid), None)
            row.append(f"{item.recall_at(5):.2f}" if item else "-")
        add("| " + " | ".join(row) + " |")
    add("")

    add("### Recall@5 by question class")
    add("")
    add("The aggregate above mixes two different measurements. `single_hop` and "
        "`multi_hop` ask what retrieval is designed to do: find the passage that "
        "answers the question. `false_premise` asks something retrieval is structurally "
        "bad at, and the split makes that visible instead of burying it in a mean.")
    add("")
    cls_of = {i.id: i.cls for i in labels.items}
    classes = ["single_hop", "multi_hop", "false_premise"]
    add("| Config | " + " | ".join(f"{c} (n={sum(1 for i in results[0].items if cls_of.get(i.item_id) == c)})"
                                   for c in classes) + " |")
    add("|---" * (len(classes) + 1) + "|")
    for res in results:
        row = [CONFIG_LABELS.get(res.config, res.config)]
        for c in classes:
            vals = [i.recall_at(5) for i in res.items if cls_of.get(i.item_id) == c]
            row.append(f"{sum(vals) / len(vals):.3f}" if vals else "-")
        add("| " + " | ".join(row) + " |")
    add("")
    add("> **`q11_nf4_attributed_to_lora` scores 0.00 on every configuration, and that "
        "is the honest and expected result.** The question asks which section of *the "
        "LoRA paper* describes NF4 quantisation. NF4 belongs to QLoRA; LoRA contains no "
        "quantisation scheme at all. Because the question names the wrong paper, the "
        "query text itself steers both retrievers straight into LoRA, and the QLoRA "
        "chunks that would correct the premise never reach the top 5. No amount of "
        "retrieval tuning fixes this — the premise is wrong, so the best passage for "
        "the query as asked is not the passage that answers it.")
    add("")
    add("This is a finding about the architecture, not a bug to tune away: **correcting "
        "a false premise is not a retrieval problem.** It requires the agent to notice "
        "that the retrieved evidence does not support what the question assumes, which "
        "is the sufficiency judge's job at Step 11 and the abstention path's job at "
        "Step 7 — both downstream of everything measured here. The retrieval numbers "
        "should be read as: retrieval finds the right passage for well-posed questions, "
        "and the false-premise case is deliberately handed to a later stage.")
    add("")

    if evidence is not None:
        add("## 2 · Measured routing thresholds")
        add("")
        add("Thresholds are read off the observed cross-encoder score distribution on "
            "this corpus. They are not carried over from a previous project: a "
            "different corpus produces a different distribution, and reusing a number "
            "across the two is how routing silently degrades.")
        add("")
        add("**How the populations were built.** Two decisions need two populations. "
            "*Routing* looks at one number per question -- the top rerank score on the "
            "slate -- so its populations hold one score per question. *Verification* "
            "looks at one (sentence, chunk) pair at a time, so its populations hold one "
            "score per chunk. Deriving a routing threshold from the per-pair "
            "distribution is a category error: a question whose best gold chunk scores "
            "0.99 routes to ANSWER regardless of whether its third gold chunk scores "
            "0.18. Positives are the gold chunks of "
            "answerable questions. Negatives are every chunk retrieved for a *control* "
            "question — a question the corpus cannot answer at all. Taking "
            "\"non-gold chunks retrieved for an answerable question\" as the negative "
            "population instead would be badly contaminated, because a chunk that was "
            "not listed as gold is very often still relevant. The controls have no "
            "correct answer anywhere in the corpus, so every chunk retrieved for them "
            "is a genuine negative.")
        add("")
        for pop in (evidence.routing_positives, evidence.routing_negatives,
                    evidence.pair_positives, evidence.pair_negatives):
            s = pop.summary()
            add(f"**{pop.name}** (n={pop.n})")
            add("")
            add("```")
            add("  " + "  ".join(f"{k}={v:.3f}" if k != "n" else f"n={int(v)}"
                                 for k, v in s.items()))
            for line in histogram(pop):
                add(line)
            add("```")
            add("")

        add("### Sensitivity sweep")
        add("")
        add("A point estimate drawn from this many positives would be a number with no "
            "error bars presented as though it had them. The curve shows how sharply "
            "the routing actually depends on the threshold.")
        add("")
        add("| tau | gold kept | control rejected | balanced |")
        add("|---:|---:|---:|---:|")
        for tau, keep, rej in zip(evidence.sweep.taus,
                                  evidence.sweep.positive_retention,
                                  evidence.sweep.negative_rejection):
            if round(tau * 40) % 4:
                continue
            add(f"| {tau:.2f} | {keep:.1%} | {rej:.1%} | {(keep + rej) / 2:.1%} |")
        add("")
        best_tau, best_bal = evidence.sweep.best_f1()
        add(f"Balanced-accuracy peak at **tau = {best_tau:.2f}** ({best_bal:.1%}).")
        add("")
        add("| Threshold | Value | How it was derived | Used for |")
        add("|---|---:|---|---|")
        for name, value, use in (
            ("TAU_LOW", evidence.tau_low, "below this, refuse"),
            ("TAU_HIGH", evidence.tau_high, "above this, answer directly"),
            ("TAU_VERIFY", evidence.tau_verify,
             "groundedness floor for one cited sentence"),
        ):
            add(f"| `{name}` | {value} | {evidence.derivation.get(name.lower(), '')} "
                f"| {use} |")
        add("")
        if not evidence.separable:
            add("> **The two routing populations overlap.** No single threshold "
                "separates answerable questions from controls on this set, so the "
                "clarify band was widened around the sweep's peak rather than a clean "
                "cut being asserted. The overlap is itself a finding and is reported "
                "rather than smoothed over.")
            add("")
        add("Between `TAU_LOW` and `TAU_HIGH` the agent asks a clarifying question "
            "rather than guessing.")
        add("")
        add("> **Stated plainly: these thresholds are tuned, not learned, and the "
            "positive population is small.** They are derived from the same question "
            "set the routing is later reported on, so route accuracy measured against "
            "them is optimistic by construction. The sweep above is published so a "
            "reader can see how much the choice actually matters rather than taking "
            "the point estimate on trust.")
        add("")

    add("## 3 · Reproducing this")
    add("")
    add("```bash")
    add("research-agent fetch      # 11 papers from the manifest")
    add("research-agent ingest     # reading-order extraction")
    add("research-agent index      # bge-m3 vectors + FTS5")
    add("research-agent labels     # validate gold labels against extracted text")
    add("research-agent eval-retrieval")
    add("```")
    add("")
    add("No API key is required for any of it.")
    add("")

    path = cfg.outputs_dir / "eval_report.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
#  Cited answers
# ---------------------------------------------------------------------------
def render_answer_markdown(answer) -> str:
    """Markdown with numbered footnotes rendered as "Paper Title · p.N".

    Footnote numbering is assigned in order of first appearance in the answer, so
    "the second source" means the second footnote a reader sees. That ordering is
    the thing a follow-up turn resolves against, so it is defined here rather than
    left to whatever order retrieval happened to return.
    """
    lines: list[str] = [f"# {answer.question}", ""]

    if answer.is_refusal:
        lines += [
            "**The sources do not contain an answer to this question.**", "",
            answer.refusal_reason or "No supporting passage was found in the corpus.",
            "", "_No citations are given, because there is nothing in the corpus to "
            "cite. This is the intended behaviour, not a failure._", "",
        ]
    else:
        order: list[str] = []
        for s in answer.sentences:
            for cid in s.chunk_ids:
                if cid not in order:
                    order.append(cid)
        number = {cid: i + 1 for i, cid in enumerate(order)}

        body = []
        for s in answer.sentences:
            marks = "".join(f"[^{number[c]}]" for c in s.chunk_ids)
            flag = " `[unverified]`" if s.status == "unverified" else ""
            body.append(f"{s.text}{marks}{flag}")
        lines += [" ".join(body), "", "## Sources", ""]

        for cid in order:
            hit = answer.hit_by_id(cid)
            label = hit.source_label if hit else cid
            lines.append(f"[^{number[cid]}]: {label} — `{cid}`")
        lines.append("")

    lines += [
        "---", "",
        f"- Provider: `{answer.provider}` · model: `{answer.model}`",
        f"- Latency: {answer.latency_ms} ms",
        f"- Passages in context: {len(answer.hits)}",
    ]
    if answer.top_rerank_score is not None:
        lines.append(f"- Top rerank score: {answer.top_rerank_score:.4f}")
    statuses: dict[str, int] = {}
    for s in answer.sentences:
        statuses[s.status] = statuses.get(s.status, 0) + 1
    if statuses:
        lines.append("- Sentence verification: " +
                     ", ".join(f"{k} {v}" for k, v in sorted(statuses.items())))
    return "\n".join(lines) + "\n"


# How much of a cited passage the committed artifact carries. Enough for a reviewer
# to check the citation by eye; far short of republishing the passage.
CITED_EXCERPT_CHARS = 600


def answer_to_dict(answer, full: bool = True) -> dict:
    """The machine-checkable form. This is the citation contract as data.

    `full=True` keeps every retrieved passage in its entirety, which the semantic
    answer cache needs to reconstruct a renderable answer. `full=False` produces the
    committed artifact: only the passages actually cited, each truncated to an
    excerpt.

    The distinction is not about file size. The corpus PDFs are deliberately not
    committed (D-006) so the repository does not redistribute anyone's paper -- and
    the first version of this function then embedded ~20,000 characters of verbatim
    paper text into every answer JSON, 8,000 of it from passages that were never
    cited. That quietly reintroduced exactly what D-006 avoided.
    """
    cited = answer.cited_chunk_ids
    sources = answer.hits if full else [h for h in answer.hits if h.chunk_id in cited]

    def source(h):
        row = {"chunk_id": h.chunk_id, "doc_id": h.doc_id, "title": h.title,
               "page_start": h.page_start, "page_end": h.page_end,
               "section": h.section, "rerank_score": h.rerank_score,
               "cited": h.chunk_id in cited}
        if full:
            row["text"] = h.text
        else:
            excerpt = " ".join(h.text.split())[:CITED_EXCERPT_CHARS]
            row["excerpt"] = excerpt + ("..." if len(h.text) > CITED_EXCERPT_CHARS else "")
        return row

    return {
        "question": answer.question,
        "insufficient_evidence": answer.insufficient_evidence,
        "refusal_reason": answer.refusal_reason,
        "sentences": [
            {"idx": s.idx, "text": s.text, "cite": s.chunk_ids,
             "verify_scores": s.verify_scores, "status": s.status}
            for s in answer.sentences
        ],
        "sources": [source(h) for h in sources],
        "n_retrieved": len(answer.hits),
        "provider": answer.provider,
        "model": answer.model,
        "latency_ms": answer.latency_ms,
        "turn_id": answer.turn_id,
    }


def write_answer(cfg, answer, item_id: str):
    """Write the .md and .json pair that gets committed to outputs/."""
    import json as _json

    out = cfg.outputs_dir / "answers"
    out.mkdir(parents=True, exist_ok=True)
    md = out / f"{item_id}.md"
    js = out / f"{item_id}.json"
    md.write_text(render_answer_markdown(answer), encoding="utf-8")
    js.write_text(
        _json.dumps(answer_to_dict(answer, full=False), indent=2, ensure_ascii=False),
        encoding="utf-8")
    return md, js


def write_full_report(cfg, results, labels, evidence, gen, convo, ledger) -> Path:
    """The complete evaluation report: both tables, every metric, traceability.

    Every number here was produced by the run that wrote the file. Where something is
    not measured it says TBD rather than carrying a plausible value.
    """
    import math

    lines: list[str] = []
    add = lines.append

    add("# Evaluation report")
    add("")
    add("Generated by `research-agent eval`. Every figure traces to this run.")
    add("")
    add(f"- Corpus fingerprint: `{labels.fingerprint_at_labelling}` · 11 papers")
    add(f"- Embedding: `{cfg.embed_model}` · Reranker: `{cfg.rerank_model}`")
    add(f"- Generation: `{cfg.ollama_model}` via Ollama")
    add(f"- Thresholds: tau_low {cfg.tau_low} · tau_high {cfg.tau_high} "
        f"· tau_verify {cfg.tau_verify}")
    add("")
    add("> **Which numbers depend on a model, and which do not.** Everything in section 1 "
        "is LLM-free: reproducible on demand, comparable across providers, and "
        "unaffected by synthesis-model variance. Everything in sections 2 and 3 moves "
        "with whichever model served the run. They are kept in separate sections rather "
        "than one table so a generation model's variance cannot masquerade as a "
        "retrieval result.")
    add("")

    # ---- 1 retrieval -----------------------------------------------------
    add("## 1 · Retrieval ablation — LLM-free")
    add("")
    add("| Config | Recall@5 | 95% CI | MRR | nDCG@10 | p50 ms | LLM calls |")
    add("|---|---:|---:|---:|---:|---:|---:|")
    for res in results:
        lo, hi = res.ci95(lambda i: i.recall_at(5))
        add(f"| {CONFIG_LABELS.get(res.config, res.config)} "
            f"| {res.mean(lambda i: i.recall_at(5)):.3f} | [{lo:.2f}, {hi:.2f}] "
            f"| {res.mean(lambda i: i.mrr()):.3f} "
            f"| {res.mean(lambda i: i.ndcg_at(10)):.3f} "
            f"| {res.p50_latency():.0f} | 0 |")
    add("")
    add("Confidence intervals are bootstrap over per-question scores. The answerable "
        "set is 8 questions, so the intervals are wide and overlapping: **the ordering "
        "is trustworthy and matches the mechanism, the exact gaps are not established "
        "by this sample.**")
    add("")

    # ---- 2 generation ----------------------------------------------------
    add("## 2 · Generation metrics — LLM-dependent")
    add("")
    add("| Metric | Value | Notes |")
    add("|---|---:|---|")
    add(f"| Citation precision | {gen.citation_precision:.3f} | verified or repaired "
        f"/ cited sentences ({gen.sentences_verified}/{gen.sentences_total}) |")
    add(f"| Abstention accuracy | {gen.abstention_accuracy:.3f} | "
        f"{gen.controls_correct}/{gen.controls_total} controls |")
    add(f"| Fact coverage (mean) | {gen.mean_fact_coverage:.3f} | case-insensitive "
        f"substring match against `expected_facts` |")
    add(f"| Route accuracy (single-turn) | {gen.route_accuracy:.3f} | |")
    add(f"| **Invented citation ids** | **{gen.invented_citations}** | a fabricated id "
        f"is a hard failure, never rendered |")
    add(f"| **Refusals carrying citations** | **{gen.refusals_with_citations}** | "
        f"structurally impossible by construction |")
    add(f"| p50 / p95 latency | {gen.latency(50):.0f} / {gen.latency(95):.0f} ms | "
        f"end-to-end per turn |")
    if gen.multi_hop_papers:
        add(f"| Papers cited per multi-hop answer | "
            f"{sum(gen.multi_hop_papers)/len(gen.multi_hop_papers):.2f} | "
            f"{gen.multi_hop_papers} |")
    add("")

    add("### Per-question")
    add("")
    add("| Question | class | expected | actual | sent | verified | papers | coverage "
        "| loops | ms |")
    add("|---|---|---|---|---:|---:|---:|---:|---:|---:|")
    for r in gen.per_item:
        cov = ("-" if (isinstance(r["coverage"], float) and math.isnan(r["coverage"]))
               else f"{r['coverage']:.2f}")
        add(f"| {r['id']} | {r['class']} | {r['expected']} | {r['actual']} "
            f"| {r['sentences']} | {r['verified']} | {r['papers']} | {cov} "
            f"| {r['loops']} | {r['ms']} |")
    add("")

    add("### Route confusion matrix")
    add("")
    conf = gen.confusion()
    actuals = sorted({a for _, a in gen.routes})
    expecteds = sorted({e for e, _ in gen.routes})
    add("| expected / actual | " + " | ".join(actuals) + " |")
    add("|---" * (len(actuals) + 1) + "|")
    for e in expecteds:
        add(f"| **{e}** | " + " | ".join(str(conf.get((e, a), 0)) for a in actuals) + " |")
    add("")
    add("`refuse` and `abstain` are both correct for a control: different mechanisms "
        "-- refused on the retrieval score, or abstained after synthesis found the "
        "evidence unsupportive -- with the same correct outcome.")
    add("")

    # ---- 3 conversation --------------------------------------------------
    if convo:
        add("## 3 · Conversation metrics — LLM-dependent")
        add("")
        add("| Metric | Value | Target |")
        add("|---|---:|---|")
        add(f"| **Condensation drift rate** | **{convo['drifted']}/{convo['turns']}** "
            f"| 0 |")
        add(f"| Route accuracy | {convo['route_correct']}/{convo['turns']} | |")
        if convo.get("coref_total"):
            add(f"| Ordinal coreference resolution | {convo['coref_ok']}/"
                f"{convo['coref_total']} | |")
        add("")
        add("| Scenario | turn | expected | actual |")
        add("|---|---:|---|---|")
        from .evaluate import _route_ok

        for sid, i, exp, act in convo["rows"]:
            # Use the same equivalence the metric uses. Marking refuse-vs-abstain as
            # a mismatch in the table while counting it correct in the number makes
            # the two disagree, and a reader will trust the table.
            mark = "" if _route_ok(exp, act) else "  <-"
            add(f"| {sid} | {i} | {exp} | {act}{mark} |")
        add("")

    # ---- 4 ops -----------------------------------------------------------
    add("## 4 · Operational")
    add("")
    add(f"- Total LLM calls in the ledger: **{ledger['total']}**")
    add(f"- Served from cache: {ledger['cached']} "
        f"(**{ledger['cache_hit_rate']:.1%}** hit rate)")
    add("")
    add("| Ladder | calls |")
    add("|---|---:|")
    for ladder, n in sorted(ledger["by_ladder"].items(), key=lambda kv: -kv[1]):
        add(f"| {ladder} | {n} |")
    add("")
    add("| Purpose | calls |")
    add("|---|---:|")
    for purpose, n in sorted(ledger["by_purpose"].items(), key=lambda kv: -kv[1]):
        add(f"| {purpose} | {n} |")
    add("")
    add("Every non-synthesis call sits on the **volume** ladder. Routing judging, "
        "condensation, rewriting or decomposition through synthesis models would "
        "exhaust reasoning quota in roughly four turns, and the failure would land on "
        "answer generation -- the one thing a reviewer sees.")
    add("")

    # ---- 5 thresholds ----------------------------------------------------
    if evidence is not None:
        add("## 5 · Measured thresholds")
        add("")
        add("| Threshold | Value | How it was derived |")
        add("|---|---:|---|")
        for name, value in (("TAU_LOW", evidence.tau_low),
                            ("TAU_HIGH", evidence.tau_high),
                            ("TAU_VERIFY", evidence.tau_verify)):
            add(f"| `{name}` | {value} | {evidence.derivation.get(name.lower(), '')} |")
        add("")
        for pop in (evidence.routing_positives, evidence.routing_negatives):
            add(f"**{pop.name}** (n={pop.n})")
            add("")
            add("```")
            s = pop.summary()
            add("  " + "  ".join(f"{k}={v:.3f}" if k != "n" else f"n={int(v)}"
                                 for k, v in s.items()))
            for line in histogram(pop):
                add(line)
            add("```")
            add("")
        add("> **The control population is four questions.** That cannot support a p95, "
            "so `TAU_HIGH` is the least well-evidenced number in the system. The "
            "thresholds are also tuned on the same questions the routing is scored "
            "against, not on held-out data, so route accuracy is optimistic by "
            "construction.")
        add("")

    # ---- 6 traceability --------------------------------------------------
    add("## 6 · Traceability")
    add("")
    add("Every number destined for the README, beside where it comes from.")
    add("")
    add("| Number | Source | LLM-dependent |")
    add("|---|---|---|")
    add("| Recall@5 / MRR / nDCG@10 | section 1, this file | no |")
    add("| Measured thresholds | section 5, this file | no |")
    add("| Citation precision | section 2, this file | yes |")
    add("| Abstention accuracy | section 2, this file | yes |")
    add("| Fact coverage | section 2, this file | yes |")
    add("| Route confusion matrix | section 2, this file | yes |")
    add("| Condensation drift rate | section 3, this file | yes |")
    add("| LLM calls per ladder, cache hit rate | section 4, this file | yes |")
    add("| Corpus statistics | `research-agent ingest` / `index` output | no |")
    add("| Sample answers | `outputs/answers/*.md` | yes |")
    add("| Conversation transcripts | `outputs/conversations/*.md` | yes |")
    add("| Gemini results | **TBD -- no Gemini call has been made** | yes |")
    add("")

    add("## 7 · Reproducing")
    add("")
    add("```bash")
    add("research-agent fetch && research-agent ingest && research-agent index")
    add("research-agent labels          # validate gold labels against extracted text")
    add("research-agent eval-retrieval  # LLM-free, zero quota")
    add("research-agent eval            # full, needs Ollama")
    add("```")
    add("")
    add("No API key is required for any of it.")

    path = cfg.outputs_dir / "eval_report.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_turn(cfg, turn, item_id: str):
    """Write the artifact for ANY outcome, including a refusal or a clarification.

    A refusal decided by the router never produces an `Answer` object, so an earlier
    version wrote nothing at all for it -- four of the twelve deliverables were
    silently missing, and those four are the abstention evidence, which is the part
    of the brief most submissions skip. An honest refusal is a result, not the
    absence of one.
    """
    import json as _json

    if turn.answer is not None:
        return write_answer(cfg, turn.answer, item_id)

    out = cfg.outputs_dir / "answers"
    out.mkdir(parents=True, exist_ok=True)
    md, js = out / f"{item_id}.md", out / f"{item_id}.json"

    is_clarify = bool(turn.clarification)
    lines = [f"# {turn.raw_text}", ""]
    if is_clarify:
        lines += ["**The question is ambiguous, so the agent asked rather than "
                  "guessing.**", "", f"> {turn.clarification}", ""]
    else:
        lines += ["**The sources do not contain an answer to this question.**", "",
                  turn.route.reason, "",
                  "_No citations are given, because there is nothing in the corpus "
                  "to cite. This is the intended behaviour, not a failure._", ""]
    lines += ["---", "",
              f"- Route: `{turn.decision}`",
              f"- Top rerank score: {turn.route.top_score:.4f}",
              f"- Retrieval loops: {turn.n_loops}",
              f"- Latency: {turn.latency_ms} ms",
              ""]
    md.write_text("\n".join(lines), encoding="utf-8")

    js.write_text(_json.dumps({
        "question": turn.raw_text,
        "route": turn.decision,
        "insufficient_evidence": not is_clarify,
        "clarification": turn.clarification,
        "reason": turn.route.reason,
        "top_rerank_score": turn.route.top_score,
        "sentences": [],
        "sources": [],
        "n_retrieval_loops": turn.n_loops,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    return md, js
