"""Markdown rendering for evaluation output and, from Step 7, for cited answers.

Every number written here comes from an object produced by a real run. Nothing in
this module invents, rounds up, or fills in a plausible-looking value.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

from .config import Config
from .evaluate import ConfigResult, ThresholdEvidence
from .labels import LabelSet
from .rerank import histogram

CONFIG_LABELS = {
    "dense": "Dense only (bge-m3)",
    "sparse": "Sparse only (FTS5 BM25)",
    "hybrid": "Hybrid, RRF k=60",
    "hybrid_rerank": "Hybrid + cross-encoder rerank",
}


def write_eval_report(
    cfg: Config,
    results: Sequence[ConfigResult],
    labels: LabelSet,
    evidence: ThresholdEvidence | None,
) -> Path:
    n_items = len(results[0].items) if results else 0
    lines: list[str] = []
    add = lines.append

    add("# Evaluation report")
    add("")
    add("Generated by `research-agent eval-retrieval`. Every figure below traces to "
        "this run; nothing is carried over from another project or estimated.")
    add("")
    add(f"- Corpus fingerprint: `{labels.fingerprint_at_labelling}`")
    add(f"- Questions: {len(labels.items)} total, **{n_items} answerable** "
        f"(scored here), {len(labels.controls)} controls")
    add(f"- Embedding model: `{cfg.embed_model}` · Reranker: `{cfg.rerank_model}`")
    add("")

    add("## 1 · Retrieval ablation")
    add("")
    add("**Every column in this table is LLM-free.** Retrieval is measured without "
        "generating a token, which is what makes it reproducible on demand, "
        "comparable across providers, and immune to the synthesis-model variance "
        "that makes generation metrics noisy. Generation-dependent columns "
        "(citation precision, abstention accuracy, fact coverage) arrive at Step 12 "
        "and are labelled as such.")
    add("")
    add("| Config | Recall@5 | 95% CI | MRR | nDCG@10 | p50 ms | p95 ms | LLM calls |")
    add("|---|---:|---:|---:|---:|---:|---:|---:|")
    for res in results:
        lo, hi = res.ci95(lambda i: i.recall_at(5))
        add(f"| {CONFIG_LABELS.get(res.config, res.config)} "
            f"| {res.mean(lambda i: i.recall_at(5)):.3f} "
            f"| [{lo:.2f}, {hi:.2f}] "
            f"| {res.mean(lambda i: i.mrr()):.3f} "
            f"| {res.mean(lambda i: i.ndcg_at(10)):.3f} "
            f"| {res.p50_latency():.0f} | {res.p95_latency():.0f} | 0 |")
    add("")
    add(f"> **On the confidence intervals.** The answerable set is {n_items} questions, "
        f"so these means are genuinely uncertain and the intervals are wide. They are "
        f"bootstrap intervals over the per-question scores, printed rather than "
        f"omitted: a bare mean over {n_items} items would imply a precision the sample "
        f"cannot support. Differences smaller than the interval width are not "
        f"differences.")
    add("")

    add("### Per-question Recall@5")
    add("")
    add("Reported per item as well as in aggregate, because with a set this small the "
        "mean can hide a single catastrophic question.")
    add("")
    header = "| Question | " + " | ".join(
        CONFIG_LABELS.get(r.config, r.config) for r in results) + " |"
    add(header)
    add("|---" * (len(results) + 1) + "|")
    ids = [i.item_id for i in results[0].items] if results else []
    for qid in ids:
        row = [qid]
        for res in results:
            item = next((i for i in res.items if i.item_id == qid), None)
            row.append(f"{item.recall_at(5):.2f}" if item else "-")
        add("| " + " | ".join(row) + " |")
    add("")

    add("### Recall@5 by question class")
    add("")
    add("The aggregate above mixes two different measurements. `single_hop` and "
        "`multi_hop` ask what retrieval is designed to do: find the passage that "
        "answers the question. `false_premise` asks something retrieval is structurally "
        "bad at, and the split makes that visible instead of burying it in a mean.")
    add("")
    cls_of = {i.id: i.cls for i in labels.items}
    classes = ["single_hop", "multi_hop", "false_premise"]
    add("| Config | " + " | ".join(f"{c} (n={sum(1 for i in results[0].items if cls_of.get(i.item_id) == c)})"
                                   for c in classes) + " |")
    add("|---" * (len(classes) + 1) + "|")
    for res in results:
        row = [CONFIG_LABELS.get(res.config, res.config)]
        for c in classes:
            vals = [i.recall_at(5) for i in res.items if cls_of.get(i.item_id) == c]
            row.append(f"{sum(vals) / len(vals):.3f}" if vals else "-")
        add("| " + " | ".join(row) + " |")
    add("")
    add("> **`q11_nf4_attributed_to_lora` scores 0.00 on every configuration, and that "
        "is the honest and expected result.** The question asks which section of *the "
        "LoRA paper* describes NF4 quantisation. NF4 belongs to QLoRA; LoRA contains no "
        "quantisation scheme at all. Because the question names the wrong paper, the "
        "query text itself steers both retrievers straight into LoRA, and the QLoRA "
        "chunks that would correct the premise never reach the top 5. No amount of "
        "retrieval tuning fixes this — the premise is wrong, so the best passage for "
        "the query as asked is not the passage that answers it.")
    add("")
    add("This is a finding about the architecture, not a bug to tune away: **correcting "
        "a false premise is not a retrieval problem.** It requires the agent to notice "
        "that the retrieved evidence does not support what the question assumes, which "
        "is the sufficiency judge's job at Step 11 and the abstention path's job at "
        "Step 7 — both downstream of everything measured here. The retrieval numbers "
        "should be read as: retrieval finds the right passage for well-posed questions, "
        "and the false-premise case is deliberately handed to a later stage.")
    add("")

    if evidence is not None:
        add("## 2 · Measured routing thresholds")
        add("")
        add("Thresholds are read off the observed cross-encoder score distribution on "
            "this corpus. They are not carried over from a previous project: a "
            "different corpus produces a different distribution, and reusing a number "
            "across the two is how routing silently degrades.")
        add("")
        add("**How the populations were built.** Two decisions need two populations. "
            "*Routing* looks at one number per question -- the top rerank score on the "
            "slate -- so its populations hold one score per question. *Verification* "
            "looks at one (sentence, chunk) pair at a time, so its populations hold one "
            "score per chunk. Deriving a routing threshold from the per-pair "
            "distribution is a category error: a question whose best gold chunk scores "
            "0.99 routes to ANSWER regardless of whether its third gold chunk scores "
            "0.18. Positives are the gold chunks of "
            "answerable questions. Negatives are every chunk retrieved for a *control* "
            "question — a question the corpus cannot answer at all. Taking "
            "\"non-gold chunks retrieved for an answerable question\" as the negative "
            "population instead would be badly contaminated, because a chunk that was "
            "not listed as gold is very often still relevant. The controls have no "
            "correct answer anywhere in the corpus, so every chunk retrieved for them "
            "is a genuine negative.")
        add("")
        for pop in (evidence.routing_positives, evidence.routing_negatives,
                    evidence.pair_positives, evidence.pair_negatives):
            s = pop.summary()
            add(f"**{pop.name}** (n={pop.n})")
            add("")
            add("```")
            add("  " + "  ".join(f"{k}={v:.3f}" if k != "n" else f"n={int(v)}"
                                 for k, v in s.items()))
            for line in histogram(pop):
                add(line)
            add("```")
            add("")

        add("### Sensitivity sweep")
        add("")
        add("A point estimate drawn from this many positives would be a number with no "
            "error bars presented as though it had them. The curve shows how sharply "
            "the routing actually depends on the threshold.")
        add("")
        add("| tau | gold kept | control rejected | balanced |")
        add("|---:|---:|---:|---:|")
        for tau, keep, rej in zip(evidence.sweep.taus,
                                  evidence.sweep.positive_retention,
                                  evidence.sweep.negative_rejection):
            if round(tau * 40) % 4:
                continue
            add(f"| {tau:.2f} | {keep:.1%} | {rej:.1%} | {(keep + rej) / 2:.1%} |")
        add("")
        best_tau, best_bal = evidence.sweep.best_f1()
        add(f"Balanced-accuracy peak at **tau = {best_tau:.2f}** ({best_bal:.1%}).")
        add("")
        add("| Threshold | Value | How it was derived | Used for |")
        add("|---|---:|---|---|")
        for name, value, use in (
            ("TAU_LOW", evidence.tau_low, "below this, refuse"),
            ("TAU_HIGH", evidence.tau_high, "above this, answer directly"),
            ("TAU_VERIFY", evidence.tau_verify,
             "groundedness floor for one cited sentence"),
        ):
            add(f"| `{name}` | {value} | {evidence.derivation.get(name.lower(), '')} "
                f"| {use} |")
        add("")
        if not evidence.separable:
            add("> **The two routing populations overlap.** No single threshold "
                "separates answerable questions from controls on this set, so the "
                "clarify band was widened around the sweep's peak rather than a clean "
                "cut being asserted. The overlap is itself a finding and is reported "
                "rather than smoothed over.")
            add("")
        add("Between `TAU_LOW` and `TAU_HIGH` the agent asks a clarifying question "
            "rather than guessing.")
        add("")
        add("> **Stated plainly: these thresholds are tuned, not learned, and the "
            "positive population is small.** They are derived from the same question "
            "set the routing is later reported on, so route accuracy measured against "
            "them is optimistic by construction. The sweep above is published so a "
            "reader can see how much the choice actually matters rather than taking "
            "the point estimate on trust.")
        add("")

    add("## 3 · Reproducing this")
    add("")
    add("```bash")
    add("research-agent fetch      # 11 papers from the manifest")
    add("research-agent ingest     # reading-order extraction")
    add("research-agent index      # bge-m3 vectors + FTS5")
    add("research-agent labels     # validate gold labels against extracted text")
    add("research-agent eval-retrieval")
    add("```")
    add("")
    add("No API key is required for any of it.")
    add("")

    path = cfg.outputs_dir / "eval_report.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
